# Generated by Django 6.0.6 on 2026-06-07 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('active_branch_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchNodeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compressed_payload', models.JSONField(blank=True, null=True)),
                ('compressed_through', models.PositiveIntegerField()),
                ('visible_end', models.PositiveIntegerField(blank=True, null=True)),
                ('child_order', models.JSONField(default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_nodes', to='chat.branchnoderecord')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_nodes', to='chat.chatsession')),
            ],
            options={
                'ordering': ['compressed_through'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.project'),
        ),
        migrations.CreateModel(
            name='StoredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('message_type', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('project', 'name'), name='uniq_named_session_per_project'),
        ),
        migrations.AddConstraint(
            model_name='storedmessage',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='uniq_message_position_per_session'),
        ),
    ]
