"""Composer — thread-based agents with typed streaming."""

from .agent import (
    Agent,
    MCPClient,
    MCPPromptInfo,
    MCPResourceInfo,
    StreamEvent,
    StreamEventKind,
    StreamEventProcessor,
    ThinkingEvent,
    AssistantEvent,
    ToolCallEvent,
    ToolResultEvent,
    ToolCall,
    ToolResult,
    combine_tools,
    extract_thinking,
    extract_assistant_text,
)
from .tools import run_tool_call
from .vector import Vector
from .thread import (
    Thread,
    HumanMessage,
    AIMessage,
    SystemMessage,
    ToolMessage,
    CompressedMessage,
    UpdateMessage,
    Message,
    EncoderType,
    TokenCalculator,
)

__all__ = [
    "Agent",
    "Vector",
    "MCPClient",
    "MCPPromptInfo",
    "MCPResourceInfo",
    "Thread",
    "HumanMessage",
    "AIMessage",
    "SystemMessage",
    "ToolMessage",
    "CompressedMessage",
    "UpdateMessage",
    "Message",
    "EncoderType",
    "TokenCalculator",
    "ThinkingEvent",
    "AssistantEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "StreamEvent",
    "StreamEventKind",
    "StreamEventProcessor",
    "ToolCall",
    "ToolResult",
    "combine_tools",
    "run_tool_call",
    "extract_thinking",
    "extract_assistant_text",
]
